In [2]:
## Data Analysis libraries
import pandas as pd
import numpy as np

## Data Visulaization Libraries
import matplotlib.pyplot as plt
import seaborn as sns

In [8]:
## Code-1:- Create a null vector of size 10 but the fifth value which is 1
null_vector=np.zeros(10)
null_vector[4]=1
null_vector

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [9]:
## Code-2:- Create a vector with values ranging from 10 to 49
vector=np.arange(10,49)
vector

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

In [10]:
## Code-3:- Create a 3x3 matrix with values ranging from 0 to 8
matrix = np.arange(0,9).reshape(3,3)
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [16]:
## Code-4:- Find indices of non-zero elements from [1,2,0,0,4,0]
arr1=np.array([1,2,0,0,4,0])
arr1
print("All index value of 0 is: ", np.where(arr1 == 0)[0])

All index value of 0 is:  [2 3 5]


In [23]:
## Code-5:- Create a 10x10 array with random values and find the minimum and maximum values.
arr=np.random.randint(100,size=(10,10))
arr

array([[95, 34, 70, 80,  8, 23, 89, 50, 61, 74],
       [19, 77, 30, 75, 76, 46, 89, 97, 87, 47],
       [81, 89, 10, 52, 41, 75,  7, 76, 77, 59],
       [82,  4, 25, 48, 85, 75, 41, 93, 66, 60],
       [ 0, 43, 72, 20, 11, 90, 77, 12,  3, 43],
       [ 6, 93, 17, 40, 81, 18, 67, 94, 79, 36],
       [87, 72, 37, 46, 94, 21, 15, 24,  9,  4],
       [16,  4, 43, 43, 12, 24, 10,  5,  5, 43],
       [59, 11, 34, 75, 31, 37, 62, 94, 10, 47],
       [43, 54, 77, 13, 67,  6, 94,  5,  5, 49]])

In [24]:
print("The maximum value is ",np.max(arr))
print("The minimum value is ",np.min(arr))

The maximum value is  97
The minimum value is  0


In [26]:
## Code-6:- Create a random vector of size 30 and find the mean value.
ran_vec=np.random.randint(30,size=30)
ran_vec

array([ 1, 19, 20,  0, 18,  4, 20,  6, 17,  4, 17, 28, 24,  5,  6, 12, 11,
       12, 10, 18,  9, 12, 18,  8, 19, 21, 17, 24,  2,  8])

In [28]:
print("The mean value of random vector is ",np.mean(ran_vec))

The mean value of random vector is  13.0
